#!/bin/bash
set -eu


### ----------------------------------------------------------------------------
### Main
### ----------------------------------------------------------------------------

(
echo "---"
echo "kit:"
echo "  name:     $GENESIS_KIT_NAME"
echo "  version:  $GENESIS_KIT_VERSION"
echo "  features: []"

genesis_config_block

echo "params: {}"

) > "$GENESIS_ROOT/$GENESIS_ENVIRONMENT.yml"

offer_environment_editor

# vim:foldmethod=marker
